# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # you may remove this if you don't use vgo
    #- go mod download
    # you may remove this if you don't need go generate
    #- go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    binary: "share"
archives:
  - id: multi
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
brews:
  - tap:
      owner: mschneider82
      name: sharecmd
    folder: Formula
    homepage: https://github.com/mschneider82/sharecmd
    description: Share your files using Cloudproviders with just one command
    test: |
      system "#{bin}/share --help"
nfpms:
  - file_name_template: "{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    homepage: https://github.com/mschneider82/sharecmd
    description: Share your files with your friends using Cloudproviders with just one command.
    maintainer: Matthias Schneider <ms@wck.biz>
    license: Apache
    formats:
      - deb
      - rpm
checksum:
  name_template: "checksums.txt"
#snapcrafts:
#  -
#    name_template: 'share_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
#    summary: Share your files using Cloudproviders with just one command
#    description: |
#      Share uploads the file to the configured cloud provider and does a
#      public share of the file for anyone who has the link. The link will be
#      copyed to system clipboard (windows/linux/macos)
#      https://github.com/mschneider82/sharecmd
#    grade: stable
#    confinement: strict
#    publish: false
#    #true
#    name: share
#    apps:
#      share:
#        plugs: ["home", "network", "x11"]
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
