# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sharecmd < Formula
  desc "Share your files using cloud providers with just one command."
  homepage "https://github.com/mschneider82/sharecmd"
  version "0.0.150"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mschneider82/sharecmd/releases/download/v0.0.150/sharecmd_Darwin_x86_64.tar.gz"
      sha256 "040bf4ed6023c3f656cea8d29e23de1352747ce857d9655f3108d11e3001d8af"

      define_method(:install) do
        bin.install "share"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mschneider82/sharecmd/releases/download/v0.0.150/sharecmd_Darwin_arm64.tar.gz"
      sha256 "1d22ef538d3530ea22ecdf1120a98c995f75030d954c9a2bb98e3d3e24687b17"

      define_method(:install) do
        bin.install "share"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mschneider82/sharecmd/releases/download/v0.0.150/sharecmd_Linux_x86_64.tar.gz"
      sha256 "34d942e3b03c4d6fc7829de7e74a2a85bfac5131bef0f1d4996e773170c0f13f"
      define_method(:install) do
        bin.install "share"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mschneider82/sharecmd/releases/download/v0.0.150/sharecmd_Linux_arm64.tar.gz"
      sha256 "9459e19c3735e8946d33ba2435e9ec3a7c3b480a4154ee3fcfabcfad3e0fe2b1"
      define_method(:install) do
        bin.install "share"
      end
    end
  end

  test do
    system "#{bin}/share", "--version"
  end
end
