# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sharecmd < Formula
  desc "Share your files using Cloudproviders with just one command"
  homepage "https://github.com/mschneider82/sharecmd"
  version "0.0.109"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mschneider82/sharecmd/releases/download/v0.0.109/sharecmd_0.0.109_Darwin_x86_64.tar.gz"
      sha256 "1b6af4194e7249a5805e19efa548e89613df18702415fef7663aa31ad1eea2cf"

      def install
        bin.install "share"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mschneider82/sharecmd/releases/download/v0.0.109/sharecmd_0.0.109_Darwin_arm64.tar.gz"
      sha256 "772eb5393f4fdf9b8893f05fe7a40e13eb4546d9b1b6b81572bdb590c6780d6c"

      def install
        bin.install "share"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/mschneider82/sharecmd/releases/download/v0.0.109/sharecmd_0.0.109_Linux_armv6.tar.gz"
      sha256 "997c7b79eb2dd6f9779e617c8231e81080d2df3eba3c794be47d9ceee9d57cfe"

      def install
        bin.install "share"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mschneider82/sharecmd/releases/download/v0.0.109/sharecmd_0.0.109_Linux_arm64.tar.gz"
      sha256 "d235211dc07e8d3f496cca42b8cf4497052017fc93038b0a6fd3cd9a527a879f"

      def install
        bin.install "share"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mschneider82/sharecmd/releases/download/v0.0.109/sharecmd_0.0.109_Linux_x86_64.tar.gz"
      sha256 "1e90067cf8c4bbf604ead8630b9fddb1a42fe8ee378545b9d913e274ebd0a9f7"

      def install
        bin.install "share"
      end
    end
  end

  test do
    system "#{bin}/share --help"
  end
end
