name: share
base: core24
adopt-info: share
summary: Share your files using Cloudproviders with just one command
description: |
  Share uploads the file to the configured cloud provider and does a
  public share of the file for anyone who has the link. The link will be
  copied to system clipboard (windows/linux/macos).
  https://github.com/mschneider82/sharecmd

grade: stable
confinement: strict

apps:
  share:
    command: bin/share
    plugs:
      - home
      - network
      - x11
      - desktop
      - desktop-legacy
      - unity7
      - wayland

parts:
  share:
    plugin: go
    source: .
    build-snaps:
      - go/latest/stable
    build-environment:
      - CGO_ENABLED: "0"
    stage-packages:
      - xclip
    override-pull: |
      craftctl default
      VERSION=$(git describe --tags --abbrev=0 2>/dev/null || echo "0.0.0")
      VERSION=${VERSION#v}
      craftctl set version="$VERSION"
